### ISSUE TITLE
TP Preview (258) on launch alters size/location of previously saved document.

### ISSUE THREAD

**Issue by ccstone** [hbsw/tp-issues#327] opened 2016-09-02 20:47 UTC

**Comment by ccstone** [comment] 2016-09-02 20:50
This may be because a blank document was created on launch that was sized and positioned differently than my preference.

**Comment by jessegrosjean** [comment] 2016-09-23 15:14
Can you try the latest release and see if you still notice the problem? And if so explain it in a little more detail ... windows seem to restore in the correct location for me. Thanks!

**Comment by jessegrosjean** [comment] 2016-09-29 22:06
Marking this as done as I can't reproduce

**Closed** 2016-09-29 22:06 UTC

**Comment by ccstone** [comment] 2016-09-30 00:04
Seems to be working correctly in the latest build – TaskPaper 3.5 Preview (269).
